# Generated by Django 3.1 on 2021-01-19 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210119_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser digitado no formato: '+258849293949'. São permitidos até 13 dígitos.", regex='^\\+?258?\\d{9,13}$')]),
        ),
        migrations.AddField(
            model_name='store',
            name='province',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='street_address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
