# Generated by Django 2.2.2 on 2019-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='company_logo/default.png', upload_to='company_logo/'),
        ),
    ]
