# Generated by Django 2.2.2 on 2019-10-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190930_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comercial_name',
            new_name='commercial_name',
        ),
    ]
