# Generated by Django 2.2.2 on 2019-10-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191024_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.Category'),
        ),
    ]
