# Generated by Django 2.2.2 on 2019-10-16 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191016_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+258849293949'. Up to 15 digits allowed.", regex='^\\+?258?\\d{9,13}$')]),
        ),
    ]
