# Generated by Django 2.2.2 on 2019-12-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191218_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.CharField(default='3YFR6zCzFZwZxAhbc06CK6INMHfNHVD0', editable=False, max_length=4),
        ),
    ]
