# Generated by Django 3.1 on 2021-01-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_store_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='store',
            name='twitter',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
