# Generated by Django 2.2.2 on 2019-12-18 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191218_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.CharField(default='MfgiMdRACCVyWRr64r3yKhkr89bPkPO7', editable=False, max_length=4),
        ),
        migrations.RemoveField(
            model_name='referrallink',
            name='user',
        ),
        migrations.AddField(
            model_name='referrallink',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
