# Generated by Django 2.2.2 on 2019-12-18 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191218_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.CharField(default='3zwD5m5LeO9EmvhH0agqd2pdIfUOTWDM', editable=False, max_length=4),
        ),
        migrations.RemoveField(
            model_name='referrallink',
            name='user',
        ),
        migrations.AddField(
            model_name='referrallink',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
