# Generated by Django 2.2.2 on 2019-12-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191218_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.CharField(default='My6H5mh0BeHrnfZmpHFKYtXJdCtltLkQ', editable=False, max_length=4),
        ),
    ]
