# Generated by Django 2.2.2 on 2019-12-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191218_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.CharField(default='EasMZRt8ueaBDFMpb9dGOCkzdTD0ASBk', editable=False, max_length=4),
        ),
    ]
