# Generated by Django 2.2.2 on 2019-12-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191218_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrallink',
            old_name='referral_link',
            new_name='link',
        ),
        migrations.AddField(
            model_name='referrallink',
            name='referral',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.CharField(default='00iIFUqwM2xs17ry11NLDqhLVF0eZWFm', editable=False, max_length=4),
        ),
    ]
