# Generated by Django 2.2.2 on 2019-12-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191218_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrallink',
            name='user',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='ReferralLink',
        ),
    ]
