# Generated by Django 3.0.6 on 2020-11-23 20:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200514_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.RemoveField(
            model_name='donation',
            name='price',
        ),
        migrations.AddField(
            model_name='donation',
            name='price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DonationPrice',
        ),
    ]
