# Generated by Django 2.2.2 on 2020-11-25 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201123_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='número_de_telefone',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser digitado no formato: '841234567'. São permitidos até 9 dígitos.", regex='^\\+?84?\\d{8,8}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Order'),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
