# Generated by Django 2.2.2 on 2020-11-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20201125_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
