# Generated by Django 3.1 on 2021-01-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_product_store'),
        ('payment', '0006_payment_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.orderproduct'),
        ),
    ]
