# Generated by Django 2.2.2 on 2019-12-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='referral',
        ),
    ]
