# Generated by Django 2.2.2 on 2019-10-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='referral',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
