# Generated by Django 2.2.2 on 2019-10-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_categories_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descont',
            new_name='discount',
        ),
    ]
