# Generated by Django 2.2.2 on 2019-10-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191031_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typediscount',
            name='number',
        ),
        migrations.RemoveField(
            model_name='typediscount',
            name='total_number',
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='total_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
