# Generated by Django 2.2.2 on 2020-11-26 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='número_de_telefone',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser digitado no formato: '841234567'. São permitidos até 9 dígitos.", regex='^\\+?84?\\d{8,8}$')]),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='número_de_telefone',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser digitado no formato: '841234567'. São permitidos até 9 dígitos.", regex='^\\+?84?\\d{8,8}$')]),
        ),
    ]
