# Generated by Django 2.2.2 on 2019-12-19 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20191219_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referred',
            new_name='ReferredLink',
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.CharField(default='ZDWROoUhF1QSo2hLJRgrQH2Cnpy9Jg6V', editable=False, max_length=4),
        ),
    ]
