# Generated by Django 2.2.2 on 2020-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201126_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
