# Generated by Django 2.2.2 on 2019-12-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191223_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.CharField(default='qPxPJjtTSDn5eTsNl9UshdZHSc5q9X0j', editable=False, max_length=4),
        ),
    ]
