# Generated by Django 2.2.2 on 2019-12-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20191223_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.CharField(default='cneTd1MuS58AhKNtNLzyoiUZ77nX8VOa', editable=False, max_length=4),
        ),
    ]
