# Generated by Django 2.2.2 on 2019-12-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20191226_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.TextField(default='uSeQMofCsXD0uBFqH3xAHzCcaKW6sMbm', editable=False, max_length=4),
        ),
    ]
