# Generated by Django 2.2.2 on 2020-01-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20191228_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='discount_price_per_click',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='total_number',
            new_name='total_number_of_click',
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.TextField(default='QsKLWxmi9OvVb6st3iXm', editable=False, max_length=1000),
        ),
    ]
