# Generated by Django 2.2.2 on 2020-01-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200102_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='type_of_discount',
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.TextField(default='ZniwbUMrkDEZXbx8bvSz', editable=False, max_length=1000),
        ),
    ]
