# Generated by Django 2.2.2 on 2020-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200102_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.TextField(default='j1gmHyEaH0m1yvNs3ceb', editable=False, max_length=1000),
        ),
    ]
