# Generated by Django 3.1 on 2021-01-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
    ]
