# Generated by Django 2.2.2 on 2020-01-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200102_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.TextField(default='z9MY828JsUrK3KCOStyp', editable=False, max_length=1000),
        ),
    ]
