# Generated by Django 2.2.2 on 2020-01-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200113_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price_per_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.TextField(default='h2FxqPBNLP7ijj7vPeGy', editable=False, max_length=1000),
        ),
    ]
