# Generated by Django 2.2.2 on 2020-03-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200115_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='qrcode',
            field=models.ImageField(default=1, upload_to='qrcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.TextField(default='MMf0wbtTcZyCkWWNSlFv', editable=False, max_length=1000),
        ),
    ]
