# Generated by Django 2.2.2 on 2020-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200306_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrallink',
            name='qrcode_image',
        ),
        migrations.AddField(
            model_name='order',
            name='qrcode_image',
            field=models.ImageField(default=1, upload_to='qrcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.TextField(default='g1NwrUKF9KUKwQCbJIn4', editable=False, max_length=1000),
        ),
    ]
