# Generated by Django 2.2.2 on 2020-03-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200306_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_token',
            field=models.TextField(default='DeuB9dSAKr90AV0DZHkG', editable=False, max_length=1000),
        ),
    ]
